// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOjgB4lJBmmx1chcto4fMjMnWUN_M2Oyg',
    appId: '1:516548857682:web:0e7383052986919acd748b',
    messagingSenderId: '516548857682',
    projectId: 'flutter-a414d',
    authDomain: 'flutter-a414d.firebaseapp.com',
    storageBucket: 'flutter-a414d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Mu9gHm2q0zpkySOQ-i756ehCJeT4I0A',
    appId: '1:516548857682:android:62c78af0d0ed0742cd748b',
    messagingSenderId: '516548857682',
    projectId: 'flutter-a414d',
    storageBucket: 'flutter-a414d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1RpDbPeDea8viftlLpJuKlGyGDxjlr9s',
    appId: '1:516548857682:ios:949b781952ee402ccd748b',
    messagingSenderId: '516548857682',
    projectId: 'flutter-a414d',
    storageBucket: 'flutter-a414d.appspot.com',
    androidClientId: '516548857682-dndur72id3966o1sg27qlcupngoeb7pd.apps.googleusercontent.com',
    iosClientId: '516548857682-ge3dilbhaqdnh4cv1hpiptsdhsip4g7g.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
